version: "3"
networks:
  critique-test:
    driver: bridge
services:
  local-test-db:
    image: postgres:latest
    # logging:
    #   driver: none
    environment:
      POSTGRES_DB: gqltest
      POSTGRES_USER: gqluser
      POSTGRES_PASSWORD: gqlpass
    ports:
      - "5433:5432"
    networks:
      - critique-test