// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type PaginationInput struct {
	Limit *int `json:"limit"`
	Page  *int `json:"page"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UsersCriteriaInput struct {
	Name  *string `json:"name"`
	Email *string `json:"email"`
}
